create table if not exists public.chargers (
  id bigint generated by default as identity primary key,
  charger_kw integer not null check (charger_kw > 0),
  total_units integer not null check (total_units >= 0),
  uploaded_at timestamptz not null default now()
);

create table if not exists public.load_patterns (
  id bigint generated by default as identity primary key,
  time_slot varchar(5) not null,
  base_load_percent numeric(5, 2) not null check (base_load_percent >= 0),
  charger_data jsonb not null default '{}'::jsonb,
  uploaded_at timestamptz not null default now()
);

create index if not exists load_patterns_time_slot_idx
  on public.load_patterns (time_slot);

alter table public.chargers enable row level security;
alter table public.load_patterns enable row level security;
